name: Deploy Program

on:
  workflow_dispatch:
    inputs:
      program:
        description: Program
        required: true
        default: token-auth-rules
        type: choice
        options:
          - token-auth-rules
      cluster:
        description: Cluster environment
        required: true
        default: devnet
        type: choice
        options:
          - devnet
          - mainnet-beta
      publish_crate:
        description: Release cargo crate
        required: true
        type: boolean
        default: true
      bump:
        description: Version bump
        required: true
        default: patch
        type: choice
        options:
          - patch
          - minor
          - major

env:
  CACHE: true

jobs:
  build_programs:
    name: Programs
    uses: ./.github/workflows/build-programs.yml
    secrets: inherit

  test_js:
    name: JS client
    needs: build_programs
    uses: ./.github/workflows/test-js.yml
    secrets: inherit

  deploy_program:
    name: Program / Deploy
    runs-on: ubuntu-latest
    needs: test_js
    permissions:
      contents: write
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Load environment variables
        run: cat .github/.env >> $GITHUB_ENV

      - name: Install Rust
        uses: metaplex-foundation/actions/install-rust@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}

      - name: Install Solana
        uses: metaplex-foundation/actions/install-solana@v1
        with:
          version: ${{ env.SOLANA_VERSION }}
          cache: ${{ env.CACHE }}

      - name: Set RPC
        run: |
          if [ "${{ inputs.cluster }}" == "devnet" ]; then
            echo RPC=${{ secrets.DEVNET_RPC }} >> $GITHUB_ENV
          else
            echo RPC=${{ secrets.MAINNET_RPC }} >> $GITHUB_ENV
          fi

      - name: Identify Program
        run: |
            echo DEPLOY_KEY=${{ secrets.TOKEN_AUTH_RULES_DEPLOY_KEY }} >> $GITHUB_ENV
            echo PROGRAM_ID=${{ secrets.TOKEN_AUTH_RULES_ID }} >> $GITHUB_ENV
            echo PROGRAM_NAME="mpl_token_auth_rules" >> $GITHUB_ENV

      - name: Download program builds
        uses: actions/download-artifact@v3

      - name: Deploy Program
        run: |
          echo "Deploying ${{ inputs.program }} to ${{ inputs.cluster }}"

          echo ${{ env.DEPLOY_KEY }} > ./deploy-key.json
          echo ${{ env.PROGRAM_ID }} > ./program-id.json

          solana config set -k ./deploy-key.json

          solana -v program deploy ./program-builds/programs/${{ inputs.program }}/target/deploy/${{ env.PROGRAM_NAME }}.so \
            -u ${{ env.RPC }} \
            --program-id ./program-id.json

      - name: Publish crate
        working-directory: ./programs/${{ inputs.program }}/program
        if: github.event.inputs.publish_crate == 'true'
        run: |
          cargo install cargo-release
          cargo login ${{ secrets.CRATES_TOKEN }}
          cargo release ${{ inputs.bump }} --execute
