name: Program Test

on:
  push:
    branches: [save_artifact]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  SOLANA_VERSION: 1.14.13
  RUST_TOOLCHAIN: 1.65.0

jobs:
  build-and-test-program:
    runs-on: buildjet-16vcpu-ubuntu-2204
    env:
      cache_id: program-test

    steps:
      # Setup Deps
      - uses: actions/checkout@v2
      - uses: ./.github/actions/install-linux-build-deps
      - uses: ./.github/actions/install-solana
        with:
          solana_version: ${{ env.SOLANA_VERSION }}
      - uses: ./.github/actions/install-rust
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}

      # Restore Cache from previous build/test
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ./rust/target
          key:
            ${{ env.cache_id }}-${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{
            env.RUSTC_HASH }}

      # Run test
      - name: test-program
        id: run_test
        working-directory: ./program
        run: |
          cargo +${{ env.RUST_TOOLCHAIN }} test -- --nocapture --test-threads 1
          cargo +${{ env.RUST_TOOLCHAIN }} test-bpf --version
          cargo +${{ env.RUST_TOOLCHAIN }} test-bpf -- --nocapture --test-threads 1
  save-artifact:
    runs-on: ubuntu-latest
    needs: build-and-test-program
    if: github.ref == 'refs/heads/save_artifact'
    steps:
      - uses: actions/upload-artifact@v3
        with:
          name: mpl-token-auth-rules
          path: ./