name: Test JS client

on:
  workflow_call:

env:
  CACHE: true

jobs:
  test:
    name: Test
    runs-on: buildjet-16vcpu-ubuntu-2004
    strategy:
      matrix:
        node: ["16.14", "18.x", "20.x"]
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Load environment variables
        run: cat .github/.env >> $GITHUB_ENV

      - name: Create Amman folder explicitly
        run: mkdir -p .amman/accounts

      - name: Start validator
        uses: metaplex-foundation/actions/start-validator@v1
        with:
          node: ${{ matrix.node }}
          solana: ${{ env.SOLANA_VERSION }}
          cache: ${{ env.CACHE }}

      - name: Install dependencies
        uses: metaplex-foundation/actions/install-node-dependencies@v1
        with:
          folder: ./clients/js
          cache: ${{ env.CACHE }}
          key: clients-js

      - name: Build
        working-directory: ./clients/js
        run: pnpm build

      - name: Test
        working-directory: ./clients/js
        run: pnpm test

  lint:
    name: Lint
    runs-on: buildjet-16vcpu-ubuntu-2004
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Load environment variables
        run: cat .github/.env >> $GITHUB_ENV

      - name: Install Node.js
        uses: metaplex-foundation/actions/install-node-with-pnpm@v1
        with:
          version: ${{ env.NODE_VERSION }}
          cache: ${{ env.CACHE }}

      - name: Install dependencies
        uses: metaplex-foundation/actions/install-node-dependencies@v1
        with:
          folder: ./clients/js
          cache: ${{ env.CACHE }}
          key: clients-js

      - name: Format
        working-directory: ./clients/js
        run: pnpm format

      - name: Lint
        working-directory: ./clients/js
        run: pnpm lint
